-- JBTB Casting Website Database Schema untuk Supabase
-- Compatible dengan PostgreSQL

-- Table untuk Lowongan Pekerjaan
CREATE TABLE IF NOT EXISTS jobs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR(255) NOT NULL,
  rate VARCHAR(255) NOT NULL,
  requirements TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  is_active BOOLEAN DEFAULT TRUE
);

-- Create indexes untuk jobs
CREATE INDEX IF NOT EXISTS idx_jobs_created_at ON jobs(created_at);
CREATE INDEX IF NOT EXISTS idx_jobs_is_active ON jobs(is_active);

-- Table untuk Data Pelamar
CREATE TABLE IF NOT EXISTS applicants (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  wa VARCHAR(20) NOT NULL,
  job_applied VARCHAR(255) NOT NULL,
  photo_link TEXT,
  portfolio_link TEXT,
  status VARCHAR(50) DEFAULT 'Pending',
  applied_date TIMESTAMP DEFAULT NOW(),
  updated_date TIMESTAMP DEFAULT NOW()
);

-- Create indexes untuk applicants
CREATE INDEX IF NOT EXISTS idx_applicants_job_applied ON applicants(job_applied);
CREATE INDEX IF NOT EXISTS idx_applicants_status ON applicants(status);
CREATE INDEX IF NOT EXISTS idx_applicants_applied_date ON applicants(applied_date);

-- Table untuk Admin
CREATE TABLE IF NOT EXISTS admin_users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username VARCHAR(100) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  last_login TIMESTAMP,
  is_active BOOLEAN DEFAULT TRUE
);

-- Table untuk Logs/History
CREATE TABLE IF NOT EXISTS activity_logs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  action_type VARCHAR(100) NOT NULL,
  description TEXT,
  admin_id BIGINT REFERENCES admin_users(id),
  affected_data_id BIGINT,
  affected_table VARCHAR(100),
  created_at TIMESTAMP DEFAULT NOW()
);

-- Create indexes untuk activity_logs
CREATE INDEX IF NOT EXISTS idx_activity_logs_created_at ON activity_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_activity_logs_action_type ON activity_logs(action_type);

-- Default data untuk Lowongan Pekerjaan
INSERT INTO jobs (title, rate, requirements, description) 
VALUES (
  'Pemeran Utama Film',
  'Rp 5.000.000 - 15.000.000',
  'Pria/Wanita,Usia 20-30th,Bisa Akting Menangis',
  'Kami mencari pemeran utama untuk film drama terbaru. Kandidat harus memiliki pengalaman minimal 2 tahun dalam industri film dan mampu memahami karakter dengan mendalam. Proses pengambilan akan berlangsung selama 3 bulan dengan shooting di berbagai lokasi.'
);

-- Default data untuk Pelamar
INSERT INTO applicants (name, email, wa, job_applied, photo_link, portfolio_link, status)
VALUES 
  (
    'Reza Rahadian',
    'reza.rahadian@talent.com',
    '081234567890',
    'Pemeran Utama Film',
    'https://google.com/search?q=photo',
    'https://youtube.com/watch?v=reza',
    'Pending'
  ),
  (
    'Chelsea Islan',
    'chelsea.islan@talent.com',
    '089988776655',
    'Pemeran Utama Film',
    'https://google.com/search?q=photo',
    'https://youtube.com/watch?v=chelsea',
    'Pending'
  );
